//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightSystemProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingPassenger
    {
        public int BookingId { get; set; }
        public int SerialNumber { get; set; }
        public string TicketNumber { get; set; }
        public string PassengerName { get; set; }
        public int Age { get; set; }
        public string IdCardDetails { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
