//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightSystemProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.BookingPassengers = new HashSet<BookingPassenger>();
        }
    
        public int BookingId { get; set; }
        public int CustomerId { get; set; }
        public int FlightId { get; set; }
        public string BookingNumber { get; set; }
        public System.DateTime BookingDate { get; set; }
        public System.DateTime TravelDate { get; set; }
        public int NumberOfPassengers { get; set; }
        public double BillAmount { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Flight Flight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingPassenger> BookingPassengers { get; set; }
    }
}
