//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace FlightSystemProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int FlightId { get; set; }

        [Display(Name ="Flight Number#")]
        [Required(ErrorMessage ="Please Enter Flight Number")]
        [StringLength(20,MinimumLength=4,ErrorMessage = "Flight Number should be minumum 4 letters wide")]
        public string FlightNumber { get; set; }


        [Display(Name = "Airline Name")]
        [Required(ErrorMessage = "Please Enter Airline Name")]
        [StringLength(20, MinimumLength = 1, ErrorMessage = "Airline Name should be minumum 1 letters wide")]
        public string AirlineName { get; set; }

        [Display(Name = "Source")]
        [Required(ErrorMessage = "Please Enter Source")]
        [StringLength(20, MinimumLength = 1, ErrorMessage = "Source should be minumum 1 letters wide")]
        public string Source { get; set; }

        [Display(Name = "Destination")]
        [Required(ErrorMessage = "Please Enter Destination")]
        [StringLength(20, MinimumLength = 1, ErrorMessage = "Destination should be minumum 1 letters wide")]
        public string Destination { get; set; }

        [Display(Name = "Travel Date")]
        [Required(ErrorMessage = "Please Enter Travel Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString="{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime TravelDate { get; set; }

        [Display(Name = "Seats Capacity")]
        [Required(ErrorMessage = "Please Enter Seats Capacity")]
        [Range(20,1500, ErrorMessage="Seast Capacity should be between 20 and 1500")]
        public int NumberOfSeats { get; set; }

        [Display(Name = "Ticket Fare")]
        [Required(ErrorMessage = "Please Enter Ticket Fare")]
        [Range(1, 1000000, ErrorMessage = "Ticket Fare should be between 1 and 1,00,0000")]
        public double TicketFare { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
